# Generated by Django 4.2.7 on 2023-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclasses',
            name='description',
            field=models.TextField(default='Your default description goes here'),
        ),
    ]
