# Generated by Django 4.2.7 on 2023-12-22 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gymclasses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
