# Generated by Django 4.2.7 on 2023-12-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_membership_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclasses',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/classes_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_choices',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')]),
        ),
    ]
