# Generated by Django 4.2.7 on 2023-12-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gymclasses_class_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclasses',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='classes_images'),
        ),
    ]
