# Generated by Django 4.2.7 on 2023-12-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gymclasses_class_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='display_name',
            field=models.CharField(default='Default Display Name', max_length=100),
        ),
    ]
