# Generated by Django 4.2.7 on 2023-12-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_instructorprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors_photo'),
        ),
        migrations.AlterField(
            model_name='gymclasses',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='class_images'),
        ),
    ]
