# Generated by Django 4.2.7 on 2024-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_membership_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
