# Generated by Django 4.2.7 on 2024-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_instructorprofile_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_choices',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('None', 'None')], default='None'),
        ),
    ]
