# Generated by Django 4.2.7 on 2024-01-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_membership_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='membership_type',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
    ]
