# Generated by Django 4.2.7 on 2024-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_memberprofile_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclasses',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
